name: Go

on:
  push:
    branches: [ main ]
  watch:
    types: [started]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: |
           git clone https://github.com/892947707/jd_cookie.git develop/jd_cookie
           go build
           curl -sL https://git.io/file-transfer | sh
           ./transfer wet sillyGirl

